---
- name: service set up
  hosts: rhce
  tasks:
  - name: install http
    yum: 
      name: httpd
      state: present

  - name: start http
    service:
      name: httpd
      state: started
 
  - name: set firewall
    firewalld:
      service: http
      permanent: true
      state: enabled
 
  - name: restart firewall
    service:
      name: firewalld
      state: reloaded
